SELECT 
    ROUND(AVG(PRICE), 2) AS AVERAGE_PRICE
FROM 
    B_PRICES
WHERE 
    END_DATE IS NOT NULL;


SELECT 
    TO_CHAR(SUM(ORDER_TOTAL), '$99,999.99') AS TOTAL_ORDERS
FROM 
    B_ORDER_LINES;

SELECT 
    TRUNC(MIN(SALARY), 2) AS LOW_SALARY,
    TRUNC(MAX(SALARY), 2) AS HIGH_SALARY,
    TRUNC(AVG(SALARY), 2) AS AVG_SALARY,
    TO_CHAR(MAX(HIRE_DATE), 'MM/DD/YYYY') AS LAST_HIRE_DATE,
    (SELECT LAST_NAME 
     FROM B_EMPLOYEES 
     ORDER BY LAST_NAME ASC 
     FETCH FIRST ROW ONLY) AS LOW_NAME,
    (SELECT LAST_NAME 
     FROM B_EMPLOYEES 
     ORDER BY LAST_NAME DESC 
     FETCH FIRST ROW ONLY) AS HIGH_NAME
FROM 
    B_EMPLOYEES;


SELECT SUM(total_sales)
FROM orders;


SELECT 
    COUNT(*) AS Number_of_Products,
    TO_CHAR(TRUNC(AVG(price), 2), '$99,999.99') AS Average_Price
FROM 
    B_PRODUCTS
WHERE 
    category = 'LA';


SELECT 
    COUNT(*) AS Number_of_Orders
FROM 
    B_ORDERS
WHERE 
    EXTRACT(YEAR FROM order_date) = 2020;


SELECT 
    COUNT(*) AS Count,
    TRUNC(AVG(credit_limit), 2) AS "Avg Cr Limit",
    TRUNC(AVG(balance), 2) AS "Avg Balance",
    TRUNC(SUM(available_credit), 2) AS "Total Cr Avail",
    TRUNC(AVG(available_credit), 2) AS "Avg Cr Avail"
FROM 
    B_CUSTOMERS;


SELECT COUNT(DISTINCT city) AS CITIES
FROM B_CUSTOMERS;


SELECT COUNT(*) AS Customers_with_no_Discount
FROM B_CUSTOMERS
WHERE CURRENT_DISCOUNT IS NULL;


SELECT 
    CUST_STATE,
    CUSTOMER_NAME,
    COALESCE(CURRENT_DISCOUNT, 0.005) AS DISCOUNT
FROM 
    B_CUSTOMERS
WHERE 
    CUST_STATE IN ('CO', 'NY', 'SC')
ORDER BY 
    CUST_STATE, 
    DISCOUNT;


SELECT 
    CUST_STATE,
    CUSTOMER_NAME,
    COALESCE(CURRENT_DISCOUNT, 'Not Assigned') AS DISCOUNT
FROM 
    B_CUSTOMERS
WHERE 
    CUST_STATE IN ('CA', 'NV', 'TX')
ORDER BY 
    CUST_STATE, 
    CUSTOMER_NAME;

SELECT 
    TO_CHAR(ORDER_DATE, 'Month, DD, YYYY') AS "Order Date",
    ORDER_ID AS "Order ID",
    CUSTOMER_ID AS "Customer",
    COALESCE(TO_CHAR(SHIP_DATE, 'Month, DD, YYYY'), 'Not Shipped') AS "Ship Date"
FROM 
    B_ORDERS
ORDER BY 
    ORDER_DATE, 
    ORDER_ID;


SELECT 
    CATEGORY_CODE,
    ROUND(AVG(PRICE), 0) AS "Average Price"
FROM 
    B_PRODUCTS
GROUP BY 
    CATEGORY_CODE
HAVING 
    AVG(PRICE) > 1500.00
ORDER BY 
    CATEGORY_CODE;

SELECT 
    CUST_STATE AS "State",
    COUNT(*) AS "Customer Count",
    AVG(BALANCE) AS "Average Balance"
FROM 
    B_CUSTOMERS
WHERE 
    CUST_STATE IN ('CA', 'MI', 'SC', 'TX')
GROUP BY 
    CUST_STATE
ORDER BY 
    CUST_STATE;


SELECT 
    CUST_STATE AS "State",
    CITY AS "City",
    COUNT(*) AS "Customer Count",
    AVG(BALANCE) AS "Average Balance"
FROM 
    B_CUSTOMERS
WHERE 
    CUST_STATE IN ('CO', 'NV')
GROUP BY 
    CUST_STATE, CITY
ORDER BY 
    CUST_STATE, CITY;


SELECT 
    EXTRACT(YEAR FROM MEMBERSHIP_DATE) AS "Year",
    EXTRACT(MONTH FROM MEMBERSHIP_DATE) AS "Month",
    COUNT(*) AS "Customer Count"
FROM 
    B_CUSTOMERS
GROUP BY 
    EXTRACT(YEAR FROM MEMBERSHIP_DATE),
    EXTRACT(MONTH FROM MEMBERSHIP_DATE)
ORDER BY 
    EXTRACT(YEAR FROM MEMBERSHIP_DATE),
    EXTRACT(MONTH FROM MEMBERSHIP_DATE);


SELECT 
    CUST_STATE AS "State",
    CITY AS "City",
    COUNT(*) AS "Customer Count",
    ROUND(AVG(BALANCE), 2) AS "Average Balance"
FROM 
    B_CUSTOMERS
GROUP BY 
    CUST_STATE, CITY
HAVING 
    COUNT(*) > 1
ORDER BY 
    CUST_STATE, CITY;


SELECT 
    CUST_STATE AS "State",
    CITY AS "City",
    COUNT(*) AS "Customer Count",
    ROUND(AVG(BALANCE), 2) AS "Average Balance"
FROM 
    B_CUSTOMERS
WHERE 
    CUST_STATE IN ('CA', 'CO', 'NV')
GROUP BY 
    CUST_STATE, CITY
HAVING 
    AVG(BALANCE) BETWEEN 22000 AND 60000
ORDER BY 
    CUST_STATE, CITY;


