SELECT 
    E.EMPLOYEE_ID,
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    E.HIRE_DATE
FROM 
    B_EMPLOYEES E
JOIN 
    B_DEPARTMENTS D
ON 
    E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE 
    YEAR(E.HIRE_DATE) = 2010
ORDER BY 
    E.EMPLOYEE_ID;


SELECT 
    D.DEPARTMENT_CODE,
    D.DEPARTMENT_NAME,
    COALESCE(E.FIRST_NAME, '-') AS FIRST_NAME,
    COALESCE(E.LAST_NAME, '-') AS LAST_NAME
FROM 
    B_DEPARTMENTS D
RIGHT OUTER JOIN 
    B_EMPLOYEES E
ON 
    D.DEPARTMENT_CODE = E.DEPARTMENT_CODE
ORDER BY 
    D.DEPARTMENT_CODE;


SELECT 
    E.LAST_NAME,
    E.FIRST_NAME,
    COALESCE(D.DEPARTMENT_NAME, 'Not assigned') AS DEPARTMENT
FROM 
    B_EMPLOYEES E
LEFT OUTER JOIN 
    B_DEPARTMENTS D
ON 
    E.DEPARTMENT_CODE = D.DEPARTMENT_CODE
ORDER BY 
    E.LAST_NAME;


SELECT 
    D.DEPARTMENT_NAME,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS MANAGER
FROM 
    B_DEPARTMENTS D
INNER JOIN 
    B_EMPLOYEES E
ON 
    D.MANAGER_ID = E.EMPLOYEE_ID
ORDER BY 
    D.DEPARTMENT_NAME;


SELECT 
    E.FIRST_NAME, 
    E.LAST_NAME, 
    J.MAX_SALARY, 
    J.MAX_SALARY * 12 AS YEARLY_SALARY
FROM 
    B_EMPLOYEES E
INNER JOIN 
    B_JOBS J
ON 
    E.JOB_ID = J.JOB_ID
WHERE 
    J.MAX_SALARY > 50000
ORDER BY 
    J.MAX_SALARY DESC;


SELECT 
    D.DEPARTMENT_NAME,
    E.LAST_NAME AS EMPLOYEE,
    E.FIRST_NAME AS FIRST_NAME,
    J.JOB_TITLE
FROM 
    B_EMPLOYEES E
INNER JOIN 
    B_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN 
    B_JOBS J ON E.JOB_ID = J.JOB_ID
WHERE 
    D.DEPARTMENT_NAME IN ('Video Games', 'Information Technology')
ORDER BY 
    D.DEPARTMENT_NAME, E.LAST_NAME;


SELECT 
    D.DEPARTMENT_CODE,
    D.DEPARTMENT_NAME,
    AVG(E.SALARY * 12) AS AVERAGE_YEARLY_SALARY
FROM 
    B_EMPLOYEES E
INNER JOIN 
    B_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY 
    D.DEPARTMENT_CODE, D.DEPARTMENT_NAME
HAVING 
    AVG(E.SALARY * 12) > 50000
ORDER BY 
    AVERAGE_YEARLY_SALARY DESC;


SELECT
    D.DEPARTMENT_CODE,
    D.DEPARTMENT_NAME,
    COALESCE(E.EMPLOYEE_ID, 'Not assigned') AS MANAGER,
    COALESCE(E.FIRST_NAME, '----') AS FIRST_NAME,
    COALESCE(E.LAST_NAME, '----') AS LAST_NAME
FROM
    B_DEPARTMENTS D
LEFT JOIN
    B_EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
ORDER BY
    D.DEPARTMENT_CODE;


SELECT
    W.WHSE_CITY,
    W.WHSE,
    C.CATEGORY,
    P.PRODUCT_CODE,
    P.PRODUCT_DESCRIPTION,
    I.QOH
FROM
    WAREHOUSES W
JOIN
    INVENTORY I ON W.WHSE_ID = I.WHSE_ID
JOIN
    PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
JOIN
    CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
ORDER BY
    W.WHSE_CITY,
    W.WHSE,
    C.CATEGORY,
    P.PRODUCT_CODE;


