SELECT
    E.EMPLOYEE_ID AS EMP#,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE,
    M.MANAGER_ID AS MGR#,
    CONCAT(M.FIRST_NAME, ' ', M.LAST_NAME) AS MANAGER
FROM
    B_EMPLOYEES E
JOIN
    B_MANAGERS M ON E.MANAGER_ID = M.MANAGER_ID
ORDER BY
    E.EMPLOYEE_ID;



SELECT
    E.EMPLOYEE_ID AS EMP#,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE,
    COALESCE(CONCAT(M.FIRST_NAME, ' ', M.LAST_NAME), 'Not assigned') AS MANAGER,
    COALESCE(M.MANAGER_ID, '----') AS MGR#
FROM
    B_EMPLOYEES E
LEFT JOIN
    B_MANAGERS M ON E.MANAGER_ID = M.MANAGER_ID
ORDER BY
    E.EMPLOYEE_ID;


SELECT
    E.EMPLOYEE_ID AS EMP#,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE,
    COALESCE(CONCAT(M.FIRST_NAME, ' ', M.LAST_NAME), 'Not assigned') AS MANAGER,
    COALESCE(M.MANAGER_ID, '----') AS MGR#
FROM
    B_EMPLOYEES E
LEFT JOIN
    B_MANAGERS M ON E.MANAGER_ID = M.MANAGER_ID
ORDER BY
    E.EMPLOYEE_ID;


SELECT
    M.MANAGER_ID AS Mgr#,
    CONCAT(M.FIRST_NAME, ' ', M.LAST_NAME) AS MANAGER,
    E.EMPLOYEE_ID AS Emp#,
    CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE
FROM
    B_EMPLOYEES E
JOIN
    B_MANAGERS M ON E.MANAGER_ID = M.MANAGER_ID
WHERE
    M.MANAGER_ID IN (110, 111, 112)
ORDER BY
    M.MANAGER_ID, E.EMPLOYEE_ID;


SELECT
    E1.FIRST_NAME AS EMPLOYEE,
    E1.HIRE_DATE AS EMP_HIRE_DATE,
    CONCAT(E2.FIRST_NAME, ' ', E2.LAST_NAME) AS MANAGER,
    E2.HIRE_DATE AS MGR_HIRE_DATE
FROM
    B_EMPLOYEES E1
JOIN
    B_EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE
    E1.HIRE_DATE < E2.HIRE_DATE
ORDER BY
    E1.LAST_NAME;


SELECT
    D.DEPARTMENT_NAME,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
    J.JOB_TITLE
FROM
    B_EMPLOYEES E
JOIN
    B_DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN
    B_JOBS J ON E.JOB_ID = J.JOB_ID
ORDER BY
    D.DEPARTMENT_NAME, E.LAST_NAME;


SELECT
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.ORDER_TOTAL
FROM
    B_ORDERS O
JOIN
    B_CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_NAME,
    O.ORDER_ID,
    O.ORDER_TOTAL
ORDER BY
    C.CUSTOMER_NAME,
    O.ORDER_ID;



