SELECT
    CONCAT(C.CATEGORY_ID, ' ', C.CATEGORY_DESC) AS CATEGORY_INFO,
    CONCAT(S.SERVICE_ID, ' ', S.SERVICE_DESC) AS SERVICE_INFO,
    S.PRICE
FROM
    CATEGORIES C
JOIN
    SERVICES S ON C.CATEGORY_ID = S.CATEGORY_ID
ORDER BY
    C.CATEGORY_ID,
    S.SERVICE_ID;


SELECT
    MODEL_YEAR,
    CAR_MAKE,
    PREVIOUS_OWNER
FROM
    CARS
WHERE
    MODEL_YEAR = 2015
ORDER BY
    MODEL_YEAR;


SELECT
    DEALER_NAME,
    CAR_MAKE,
    PREVIOUS_OWNER
FROM
    DEALERS_CARS
WHERE
    DEALER_NAME IN ('Bayside Autos', 'Eastside Better Used Car')
ORDER BY
    DEALER_NAME,
    CAR_MAKE,
    PREVIOUS_OWNER;


SELECT
    CONCAT(MODEL_YEAR, ' ', CAR_MAKE) AS CAR,
    DATE_ACQUIRED,
    PREVIOUS_OWNER
FROM
    CARS
WHERE
    YEAR(DATE_ACQUIRED) = 2023
ORDER BY
    CAR;


SELECT
    CONCAT(MODEL_YEAR, ' ', CAR_MAKE) AS CAR,
    CASE
        WHEN PREVIOUS_OWNER IS NULL OR PREVIOUS_OWNER = 'No previous owner on record' THEN 'No previous owner on record'
        ELSE PREVIOUS_OWNER
    END AS PREVIOUS_OWNER
FROM
    CARS
WHERE
    YEAR(DATE_ACQUIRED) = 2024
ORDER BY
    CAR;



SELECT
    DEALER_NAME,
    YEAR,
    INVENTORY_VALUE
FROM
    DEALERS
WHERE
    DEALER_ID IN (120, 206)
ORDER BY
    YEAR,
    DEALER_NAME;
