SELECT DEPARTMENT_NAME, EMPLOYEE_NAME, JOB_TITLE, MONTHLY_SALARY
FROM EMPLOYEES
WHERE JOB_TITLE IN (SELECT JOB_TITLE 
                    FROM EMPLOYEES 
                    WHERE JOB_TITLE IN ('Department Manager', 'Software Developer'))
ORDER BY DEPARTMENT_NAME, LAST_NAME;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY <= ALL (SELECT SALARY FROM EMPLOYEES WHERE SALARY > (SELECT SALARY FROM EMPLOYEES));

SELECT DEPARTMENT_NAME, EMPLOYEE_NAME, MONTHLY_SALARY
FROM EMPLOYEES
WHERE MONTHLY_SALARY = ANY (SELECT MIN(MONTHLY_SALARY) 
                             FROM EMPLOYEES 
                             GROUP BY DEPARTMENT_NAME)
ORDER BY DEPARTMENT_NAME, LAST_NAME;

SELECT DEPARTMENT_NAME, EMPLOYEE_NAME, MONTHLY_SALARY
FROM EMPLOYEES
WHERE MONTHLY_SALARY IN (SELECT MAX(MONTHLY_SALARY)
                         FROM EMPLOYEES
                         GROUP BY DEPARTMENT_NAME)
ORDER BY DEPARTMENT_NAME;

SELECT CUSTOMER_NAME, ORDER_ID, DAYS_TO_SHIP
FROM ORDERS O
WHERE DAYS_TO_SHIP > (SELECT AVG(DAYS_TO_SHIP) 
                      FROM ORDERS 
                      WHERE CUSTOMER_ID = O.CUSTOMER_ID)
ORDER BY DAYS_TO_SHIP;
